abbr -a -- amend 'git commit --amend --no-edit'
abbr -a -- cdgr 'cd (git rev-parse --show-toplevel)'
abbr -a -- ch 'chezmoi'
abbr -a -- code 'code-insiders'
abbr -a -- g 'git'
abbr -a -- ga 'git add'
abbr -a -- gaa 'git add --all'
abbr -a -- gap 'git add --patch'
abbr -a -- gau 'git add --update'
abbr -a -- gc 'git commit'
abbr -a -- gca 'git commit --amend'
abbr -a -- gg 'git graph'
abbr -a -- gd  'git diff --color-words'
abbr -a -- gds 'git diff --staged --color-words'
abbr -a -- gfa 'git fetch --all'
abbr -a -- gl 'git log --oneline'
abbr -a -- gp 'git push'
abbr -a -- gs 'git status'
abbr -a -- hm 'history --merge'
abbr -a -- ip-remote 'curl --silent ipinfo.io/ip | tee /dev/tty | pbcopy'
abbr -a -- ip-local 'ipconfig getifaddr en0 | tee /dev/tty | pbcopy'
abbr -a -- ipu 'ip-update'
abbr -a -- ll 'ls -al'
abbr -a -- stash 'git stash'
abbr -a -- tcp_states 'watch -n 1 "netstat -an | awk \'/^tcp/ { ++S[\\$NF] } END { for(a in S) print a, S[a] }\'"'
abbr -a -- tf 'terraform'
