abbr -a -- amend 'git commit --amend --no-edit'
abbr -a -- cdgr 'cd (git root)'
abbr -a -- ch 'chezmoi'
abbr -a -- code 'code-insiders'
abbr -a -- dns 'curl http://sync.afraid.org/u/SDK9tmQWwc9Mt4kXzo36SqGP/ | tee /tmp/freedns_el-sl_privatedns_org.log'
abbr -a -- g 'git'
abbr -a -- ga 'git add'
abbr -a -- gaa 'git add --all'
abbr -a -- gap 'git add --patch'
abbr -a -- gau 'git add --update'
abbr -a -- gc 'git commit'
abbr -a -- gca 'git commit --amend'
abbr -a -- gg 'git log --graph --oneline --all'
abbr -a -- gd  'git diff --color-words'
abbr -a -- gds 'git diff --staged --color-words'
abbr -a -- gfa 'git fetch --all'
abbr -a -- gl 'git log --oneline'
abbr -a -- gs 'git status'
abbr -a -- hm 'history --merge'
abbr -a -- ip-remote 'curl --silent ipinfo.io/ip | tee /dev/tty | pbcopy'
abbr -a -- ip-local 'ipconfig getifaddr en0 | tee /dev/tty | pbcopy'
abbr -a -- ip-update 'curl http://sync.afraid.org/u/SDK9tmQWwc9Mt4kXzo36SqGP/ | tee /tmp/freedns_el-sl_privatedns_org.log'
abbr -a -- ll 'ls -al'
abbr -a -- stash 'git stash'
abbr -a -- tf 'terraform'
